<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Proyectos</title>
	<?php
		include "includes/estilo.php";
	?>
</head>
<body>
	<?php
		include "includes/header.php";
		include "includes/nav.php";
		include "includes/slider.php";
	?>
	<section class="contenido">
				<h3>Problema 3 de Eliseo Nava</h3>
				<article class="articulos">	

					<font  align="center" >
				<b><h1>INCREMENTO Y DECREMENTO</h1></b>
</font>
					<figure>
						<img src="imagenes/p3.png" alt="">
						<img src="imagenes/p32.png" alt="">

					</figure>
					<h4>P3 Resultado del codigo de menor a mayor</h4>

					<div align=center><b><font color="red" size=10>
					<?php
						include "p5_benitez_06_php/formas.php";

					?>
					</div></b></font>
					<h4>P3 Resultado del codigo de mayor a menor</h4>
					<div align=center><b><font color="red" size=10>
					<?php
						include "p5_benitez_06_php/formenos.php";

					?>
					</div></b></font>


					<h4> Explicacion del codigo</h4>
										<img src="imagenes/explica.png" alt="">

					<b><p>
					HOLA Y BIENVENIDO A LA EXPLIACION DEL EJERCICIO 
					UTILIZANDO OPERADORES LOGICOS<BR>
					(ESTA EXPLICACION SERA DE LINEA POR LINEA PARA
					ASI EVITAR PIERDE EN SU EXPLICACION).<BR>
<br>EN ESTA ACTIVIDAD APESAR DE QUE SE DIO EL EJEMPLO DE COMO FUNCIONA TANTO
DE MANERA EN AUMENTO COMO SI ESTE DISMINUYERA, SE DARA UNA EXPLICACION GENERAL
(VIENDO QUE YA SABEMOS LO QUE ES ESTA ESTRUCTURA LA CUAL COMO PEQUEÑO
RECORDATORIO SABEMOS QUE ES UNA ESTRUCTURA QUE EVALUA UNA VARIABLE Y REPITE
SU CONTENIDO HASTA ENCONTRAR EL FINAL QUE HEMOS DE COLOCAR)
PUES LA FUNCION EN LOS DOS ES LA MISMA Y SOLO TIENE UN CAMBIO
QUE SE DARA EXPLICACION A CONTINUACION.....<BR>
<BR>LINEA 1:<BR> EN ESTA LINEA ABRIMOS LO QUE ES NUESTRO PHP <BR>
LINEA 2:<BR> EN ESTA LINEA QUE INICIA ES NUESTRA ESTRUCTURA FOR COMENZANDO IGUALMENTE
CON ESA PALABRA (for) SEGUIDO DE ELLA SE ABREN PARENTESIS LOS CUALES
ENCIERRAN A NUESTRA VARIABLE QUE EN NUESTRO CASO ES LA VARIABLE ($var) SEGUIDO
DE UN IGUAL EL CUAL NOS REPRESENTA QUE EL NUMERO O DATO QUE SE COLOQUE AHI
SERA CON EL QUE NUESTRA ESTRUCTURA DEBERA COMENZAR, TERMINANDO ESTO SE 
COLOCA UN PUNTO Y COMA, SEGUIDO DE ESO DE NUEVO LLAMAMOS A NUESTRA VARIABLE ($var)
DONDE COLOCAMOS JUNTO A UN SIGNO LOGICO O DE DECISION COMO QUERREMOS QUE TERMINE
YA SEA CUANDO NUESTRA VARIABLE SEA MAYOR, MENOR O IGUAL A ESE VALOR FINAL QUE COLOQUEMOS
DESPUES DE ESTE VALOR LOGICO, SEGUIDO DE ESTO SE SEPARA POR UN PUNTO Y COMA
Y COLOCAMOS EL COMO SE EJECUTARA ESTA ESTRUCTURA SI AUMENTARA (ESTO COLOCANDOLE EL SIGNO DE MAS
JUNTO AL VALOR QUE DEBE SUMARSE, EL CUAL MAYORMENTE ESTE SUELE SER UNO)O DISMINUIRA
(ESTO COLOCANDO EL SIGNO DE MENOS
JUNTO AL VALOR QUE DEBERA RESTARSE, QUE IGUAL QUE LO ANTERIOR USUALMENTE SE COLOCA EL 
NUMERO UNO ) A ESTE ULTIMO NO SE COLOCA PUNTO Y COMA SINO QUE SE SALE DE EL PARENTESIS
Y SE ABREN CORCHETES PARA DAR PASO A EL CONTENIDO O PROCEDIMIENTO
QUE SE DEBERA REALIZAR SI LAS CONDICIONES DEL FOR SON CIERTAS<BR>
</p>
<img src="imagenes/ej3.png" alt="">

<p>
LINEA 3: <BR>EN ESTA LINEA SE COLOCO UN PROCEDIMIENTO QUE SE DEBERA EJECUTAR MIENTRAS LA CONDICION ES CIERTA 
LA CUAL EN ESTE CASO ES EL COLOCAR EL VALOR DE LA VARIABLE (POR MEDIO DE UN ECHO) 
MIENTRAS ESTA PASA POR LA ESTRUCTURA CREANDO ASI 
UNA SUCESION DE NUMEROS<BR>
LINEA 4-6:<BR>EN ESTAS LINEAS SE ENCUENTRA EL CIERRE DEL CORCHETE DE NUESTRO FOR Y EL 
CIERRE DE NUESTRO PHP DANDO FIN ASI A NUESTRO PROGRAMA.

</b></p>
				</article>
		</section>
		<?php
			include "includes/footer.php";
		?>
</body>
</html>